language: node_js
node_js:
- stable
dist: trusty
sudo: true
cache:
  directories:
  - node_modules
before_install:
- npm cache verify
- npm prune
install:
- npm install
script:
- npm run ci:travis
notifications:
  email:
    recipients:
      - krbaio3@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: digital-workshop
  local_dir: dist
  skip_cleanup: true
  on: develop