/** Declaration file generated by dts-gen */
declare module 'vue-blockui' {
    const name: string;
    const props: string[];
    const staticRenderFns: any[];
    function render(): any;
    export function install(Vue: any): void;
}
